# Generated by Django 3.2.9 on 2021-12-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20211206_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='token',
            field=models.IntegerField(null=True),
        ),
    ]
