# Generated by Django 4.0.1 on 2022-01-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_num_counters_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.AddField(
            model_name='employee',
            name='counterNumber',
            field=models.IntegerField(null=True),
        ),
    ]
